# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - azure-pipelines.yml
      - MusicPlayer/*
      - CoreLib/*
      - Database/MusicPlayer/*
stages:
- stage: build_artifact
  displayName: Build artifact
  pool:
    vmImage: 'windows-2019'
  jobs:
  - job: Build

  variables:
    solution: '**/*.sln'
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Release'

    steps:
      - task: NuGetToolInstaller@1
      - task: UseDotNet@2
        displayName: 'Use .NET Core SDK 3.1'
        inputs:
          version: 3.1.x

      - task: DotNetCoreCLI@2
        displayName: 'Build'
        inputs:
          command: build
          projects: '**/MusicPlayer/*.csproj'
          arguments: '--configuration $(buildConfiguration)'

      - task: DotNetCoreCLI@2
        displayName: 'Create Publish Build'
        inputs:
          command: publish
          publishWebProjects: false
          projects: '**/MusicPlayer/*.csproj'
          arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
          zipAfterPublish: false
          modifyOutputPath: false

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifacts'
        inputs:
          PathtoPublish: '$(build.artifactstagingdirectory)'
          ArtifactName: 'music-api-drop'
        condition: succeededOrFailed()
